ignoreScripts: true
catalogMode: prefer
minimumReleaseAge: 5760 # 4 days in minutes
trustPolicy: no-downgrade
strictDepBuilds: true
blockExoticSubdeps: true

onlyBuiltDependencies:
  - esbuild
minimumReleaseAgeExclude:
  # Renovate security update: vite@8.0.5
  - vite@8.0.5
