name: check for uncommitted dist/ changes

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: setup pnpm
        uses: pnpm/action-setup@v4.0.0
        id: pnpm-install

      - name: setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: rebuild the dist/ directory
        run: |
          pnpm run build

      - name: compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

      - name: upload dist/ as an artifact
        uses: actions/upload-artifact@v4.5.0
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/
