name: test action

on:
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: run action
        uses: ./
        with:
          who-to-greet: Mona the Octocat
